const actionTypes={
    bookTypes:{
        FETCH_BOOKS_START:"FETC_BOOK_START",
        FETCH_BOOKS_SUCCESS:"FETCH_BOOKS_SUCCESS",
        FETCH_BOOKS_FAIL:"FETCH_BOOKS_FAIL"
    },
    categoryTypes:{
        FETCH_CATEGORIES_START:"FETCH_CATEGORIES_START",
        FETCH_CATEGORIES_SUCCESS:"FETCH_CATEGORIES_SUCCESS",
        FETCH_CATEGORIES_FAIL:"FETCH_CATEGORIES_FAIL"
    }
}

export default actionTypes