const actionTypes={
    bookTypes:{
        FETCH_BOOKS_START:"FETC_BOOK_START",
        FETCH_BOOKS_SUCCESS:"FETCH_BOOKS_SUCCESS",
        FETCH_BOOKS_FAIL:"FETCH_BOOKS_FAIL",
        ADD_BOOK:"ADD_BOOK",
        DELETE_BOOK:"DELETE_BOOK",
        EDIT_BOOK:"EDIT_BOOK"
    },
    categoryTypes:{
        FETCH_CATEGORIES_START:"FETCH_CATEGORIES_START",
        FETCH_CATEGORIES_SUCCESS:"FETCH_CATEGORIES_SUCCESS",
        FETCH_CATEGORIES_FAIL:"FETCH_CATEGORIES_FAIL"
    }
}

export default actionTypes